language: php

sudo: false

php:
  - 7.0

before_script:
  - composer install --dev
  - vendor/bin/ion-loader.php --load=./ion.so

script:
  - php -dextension=./ion.so vendor/bin/phpunit

after_script:
  - php vendor/bin/coveralls